export const BOOKING_STATUS = {
	PENDING: 'PENDING',
	AWAITING_OWNER_APPROVAL: 'AWAITING_OWNER_APPROVAL',
	FAILED: 'FAILED',
	CONFIRMED: 'CONFIRMED',
	CANCELLED: 'CANCELLED',
	COMPLETED: 'COMPLETED',
};

export const PAYMENT_STATUS = {
	PENDING: 'PENDING',
	FAILED: 'FAILED',
	SUCCESS: 'SUCCESS',
	REFUNDED: 'REFUNDED',
};
